name: Build and Push Gatus Image

on:
  push:
    branches:
      - main

concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true


permissions:
  id-token: write
  contents: read
  security-events: write


env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        id: build-image
        run: |
          docker build \
            -t ${{ vars.ECR_REPOSITORY }}:${{ github.sha }} \
            -f gatus/Dockerfile gatus
            
      - name: Image scan using Grype
        uses: anchore/scan-action@v6
        with:
          image: ${{ steps.build-image.outputs.image }}
          fail-build: true
          severity-cutoff: critical
          output-format: sarif
          output-file: grype-results.sarif

      - name: Upload Grype results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: grype-results.sarif

      - name: Tag and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        run: |
          docker tag ${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
            $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

          docker tag ${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
            $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest

          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest